QuanLyMoiTruong.WebApp/Controllers/BaoCaoController.cs
using Microsoft.AspNetCore.Mvc;
using QuanLyMoiTruong.Application.Requests;
using QuanLyMoiTruong.Application.ViewModels;
using QuanLyMoiTruong.WebApp.Service;

namespace QuanLyMoiTruong.WebApp.Controllers
{
    public class BaoCaoController : Controller
    {
        private readonly IBaoCaoApiClient _baoCaoApiClient;
        private readonly IConfiguration _configuration;

        public BaoCaoController(IBaoCaoApiClient baoCaoApiClient,
            IConfiguration configuration)
        {
            _baoCaoApiClient = baoCaoApiClient;
            _configuration = configuration;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> BaoCaoCapGiayPhepMoiTruong()
        {
            var request = new GiayPhepMoiTruongRequest();
            var result = await _baoCaoApiClient.SearchBaoCaoCapGiayPhepMoiTruong(request);
            var model = result.Data;
            ViewBag.Data = model;
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> BaoCaoCapGiayPhepMoiTruong(GiayPhepMoiTruongRequest request, string command)
        {
            if (command.Equals("Search"))
            {
                var result = await _baoCaoApiClient.SearchBaoCaoCapGiayPhepMoiTruong(request);
                var model = result.Data;
                ViewBag.Data = model;
            }
            else
            {
                var data = await _baoCaoApiClient.ExportBaoCaoCapGiayPhepMoiTruong(request);
                if (data.Success)
                {
                    var result = File(data.Data, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Báo cáo cấp giấy phép môi trường.xlsx");
                    return result;
                }
                return Ok(data);
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> BaoCaoChiTieuBaoVeMoiTruongKhuKinhTe()
        {
            var request = new BaoCaoBaoVeMoiTruongRequest();
            //var result = await _baoCaoApiClient.SearchBaoCaoChiTieuBaoVeMoiTruongKCN(request);
            //var model = result.Data;
            //ViewBag.Data = model;
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> BaoCaoChiTieuBaoVeMoiTruongKhuKinhTe(BaoCaoBaoVeMoiTruongRequest request, string command)
        {
            //if (command.Equals("Search"))
            //{
            //    var result = await _baoCaoApiClient.SearchBaoCaoChiTieuBaoVeMoiTruongKhuKinhTe(request);
            //    var model = result.Data;
            //    ViewBag.Data = model;
            //}
            //else
            //{
            //    var data = await _baoCaoApiClient.ExportBaoCaoChiTieuBaoVeMoiTruongKhuKinhTe(request);
            //    if (data.Success)
            //    {
            //        var result = File(data.Data, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Chỉ tiêu báo cáo môi trường đối với các KCN.xlsx");
            //        return result;
            //    }
            //    return Ok(data);
            //}
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> BaoCaoChiTieuBaoVeMoiTruongKCN()
        {
            var request = new BaoCaoBaoVeMoiTruongRequest();
            var result = await _baoCaoApiClient.SearchBaoCaoChiTieuBaoVeMoiTruongKCN(request);
            var model = result.Data;
            ViewBag.Data = model;
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> BaoCaoChiTieuBaoVeMoiTruongKCN(BaoCaoBaoVeMoiTruongRequest request, string command)
        {
            if (command.Equals("Search"))
            {
                var result = await _baoCaoApiClient.SearchBaoCaoChiTieuBaoVeMoiTruongKCN(request);
                var model = result.Data;
                ViewBag.Data = model;
            }
            else
            {
                var data = await _baoCaoApiClient.ExportBaoCaoChiTieuBaoVeMoiTruongKCN(request);
                if (data.Success)
                {
                    var result = File(data.Data, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Chỉ tiêu báo cáo môi trường đối với các KCN.xlsx");
                    return result;
                }
                return Ok(data);
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> BaoCaoCacDoanhNghiepHoatDongTrongKCN()
        {
            var request = new BaoCaoBaoVeMoiTruongRequest();
            var result = await _baoCaoApiClient.SearchBaoCaoCacDoanhNghiepHoatDongTrongKCN(request);
            var model = result.Data;
            ViewBag.Data = model;
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> BaoCaoCacDoanhNghiepHoatDongTrongKCN(BaoCaoBaoVeMoiTruongRequest request, string command)
        {
            if (command.Equals("Search"))
            {
                var result = await _baoCaoApiClient.SearchBaoCaoCacDoanhNghiepHoatDongTrongKCN(request);
                var model = result.Data;
                ViewBag.Data = model;
            }
            else
            {
                var data = await _baoCaoApiClient.ExportBaoCaoCacDoanhNghiepHoatDongTrongKCN(request);
                if (data.Success)
                {
                    var result = File(data.Data, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Danh sách các cơ sở hoạt động trong các khu công nghiệp.xlsx");
                    return result;
                }
                return Ok(data);
            }
            return View();
        }


    }
}

QuanLyMoiTruong.WebApp/Views/BaoCao/BaoCaoCacDoanhNghiepHoatDongTrongKCN.cshtml
@using QuanLyMoiTruong.Application.Requests
@model BaoCaoBaoVeMoiTruongRequest;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="pagetitle">
    <h1>Bảng 2 (Báo cáo BVMT KKT)</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
            <li class="breadcrumb-item active">Bảng 2: Danh sách các cơ sở hoạt động trong các KCN</li>
        </ol>
    </nav>
</div><!-- End Page Title -->
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <div class="row  pt-2">
                    <form asp-action="BaoCaoCacDoanhNghiepHoatDongTrongKCN" asp-controller="BaoCao" method="post" class="row g-3 needs-validation" novalidate>
                        <div class="col-6 col-md-6 col-lg-6 col-xl-8">
                            <div class="row  ttls-cm">
                                <div class="col-4">
                                    <label>Từ ngày</label>
                                    <div class="ttls-content">
                                        <input type="date" class="form-control" asp-for="TuNgay" placeholder="Từ ngày">
                                    </div>
                                </div>
                                <div class="col-4">
                                    <label>Đến ngày</label>
                                    <div class="ttls-content">
                                        <input type="date" class="form-control" asp-for="DenNgay" placeholder="Đến ngày">
                                    </div>
                                </div>
                                <div class="col-4">
                                    <label>Năm báo cáo</label>
                                    <div class="ttls-content">
                                        <select asp-for="Nam" class="form-control">
                                            <option value="0">Lựa chọn năm báo cáo</option>
                                            <option value="2018">Năm 2018</option>
                                            <option value="2019">Năm 2019</option>
                                            <option value="2020">Năm 2020</option>
                                            <option value="2021">Năm 2021</option>
                                            <option value="2022">Năm 2022</option>
                                            <option value="2023">Năm 2023</option>
                                            <option value="2024">Năm 2024</option>
                                            <option value="2025">Năm 2025</option>
                                            <option value="2026">Năm 2026</option>
                                            <option value="2027">Năm 2027</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-6 col-md-6 col-lg-6 col-xl-4">
                            <label></label>

                            <div class="ttls-cm">
                                <div class="ttls-content">
                                    <button class="btn btn-sm btn-primary waves-effect waves-light" type="submit" name="command" value="Search">
                                        <span>Tra cứu</span>
                                        <i class="fas fa-search"></i>
                                    </button>
                                    <button class="btn btn-sm btn-success waves-effect waves-light" type="submit" name="command" value="Export">
                                        <span>Xuất excel</span>
                                        <i class="fas fa-excel"></i>
                                    </button>

                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Dữ liệu báo cáo</h4>
                <table id="tbl" class="table table-bordered table-hover table-striped" style="width: 100%">
                    <thead>
                        <tr>
                            <th rowspan="2" style="width: 5%">STT</th>
                            <th rowspan="2">Tên khu công nghiệp</th>
                            <th rowspan="2">Tên dự án/cơ sở</th>
                            <th rowspan="2">Số giấy phép</th>
                            <th rowspan="2">Loại hình sản xuất/Quy mô công suất</th>
                            <th colspan="3">Nước thải</th>
                            <th colspan="2">Khí thải</th>
                            <th colspan="3">Tổng lượng CTR phát sinh</th>
                            <th rowspan="2">Tỷ lệ cây xanh</th>
                        </tr>
                        <tr>
                            <th>Tổng lượng nước thải phát sinh</th>
                            <th>Đấu nối vào HTXLNT</th>
                            <th>Tách đấu nối</th>
                            <th>Lượng khí thải phát sinh</th>
                            <th>Quan trắc khí thải tự độngliên tục</th>
                            <th>Sinh hoạt (tấn/năm)</th>
                            <th>Công nghiệp thông thường (kg/năm)</th>
                            <th>Nguy hại (kg/năm)</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (ViewBag.Data != null)
                        {
                            @for (int i = 0; i < @ViewBag.Data.Count; i++)
                            {
                                <tr>
                                    <td>@(i + 1)</td>
                                    <td>@ViewBag.Data[i].TenKhuCongNghiep</td>
                                    <td>@ViewBag.Data[i].TenDoanhNghiep</td>
                                    <td>@ViewBag.Data[i].SoGiayTo</td>
                                    <td>@ViewBag.Data[i].LoaiHinhSanXuat</td>
                                    <td>@ViewBag.Data[i].TongLuongNuocThai</td>
                                    <td>@ViewBag.Data[i].DauNoiVaoHTXLNT</td>
                                    <td>@ViewBag.Data[i].TachDauNoi</td>
                                    <td>@ViewBag.Data[i].LuongKhiThai</td>
                                    <td>@ViewBag.Data[i].QuanTracKhiThai</td>
                                    <td>@ViewBag.Data[i].ChatThaiRanSinhHoat</td>
                                    <td>@ViewBag.Data[i].ChatThaiRanCongNghiep</td>
                                    <td>@ViewBag.Data[i].ChatThaiRanNguyHai</td>
                                    <td>@ViewBag.Data[i].TyLeCayXanh</td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section Scripts{
<script type="text/javascript" src="//cdn.jsdelivr.net/momentjs/latest/moment-with-locales.min.js"></script>
}

QuanLyMoiTruong.WebApp/Views/BaoCao/BaoCaoCapGiayPhepMoiTruong.cshtml
@using QuanLyMoiTruong.Application.Requests
@model GiayPhepMoiTruongRequest;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="pagetitle">
    <h1>Báo cáo danh mục dự án/ cơ sở được cấp giấy phép môi trường</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
            <li class="breadcrumb-item active">Báo cáo danh mục dự án/ cơ sở được cấp giấy phép môi trường</li>
        </ol>
    </nav>
</div><!-- End Page Title -->
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <div class="row  pt-2">
                    <form asp-action="BaoCaoCapGiayPhepMoiTruong" asp-controller="BaoCao" method="post" class="row g-3 needs-validation" novalidate>
                        <div class="col-9 col-md-9 col-lg-9 col-xl-9">
                            <div class="row  ttls-cm">
                                <div class="col-3">
                                    <label>Từ ngày</label>
                                    <div class="ttls-content">
                                        <input type="date" class="form-control" asp-for="TuNgay" placeholder="Từ ngày">
                                    </div>
                                </div>
                                <div class="col-3">
                                    <label>Đến ngày</label>
                                    <div class="ttls-content">
                                        <input type="date" class="form-control" asp-for="DenNgay" placeholder="Đến ngày">
                                    </div>
                                </div>
                                 <div class="col-3">
                                    <label>Loại giấy phép</label>
                                    <div class="ttls-content">
                                        <select asp-for="TenGiayPhep" class="form-control">
                                            <option value="">Tất cả</option>
                                            <option value="GiayPhepMoiTruong">Giấy phép môi trường</option>
                                            <option value="BaoCaoTacDongMoiTruong">Báo cáo tác động môi trường</option>
                                        </select>
                                    </div>
                                </div>
                                 <div class="col-3">
                                    <label>Khu công nghiệp</label>
                                    <div class="ttls-content">
                                        <select asp-for="IdKhuCongNghiep" class="form-control">
                                            <option value="0">Tất cả</option>
                                            <option value="1">KCN VSIP Nghệ An</option>
                                            <option value="2">KCN WHA</option>
                                            <option value="3">KCN Nam Cấm</option>
                                            <option value="4">KCN Bắc Vinh</option>
                                            <option value="6">KCN Đông Hồi</option>
                                            <option value="7">KCN Hoàng Mai 1</option>
                                            <option value="8">KCN Thọ Lộc</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-3 col-md-3 col-lg-3 col-xl- 3">
                            <label></label>

                            <div class="ttls-cm">
                                <div class="ttls-content">
                                    <button class="btn btn-sm btn-primary waves-effect waves-light" type="submit" name="command" value="Search">
                                        <span>Tra cứu</span>
                                        <i class="fas fa-search"></i>
                                    </button>
                                    <button class="btn btn-sm btn-success waves-effect waves-light" type="submit" name="command" value="Export">
                                        <span>Xuất excel</span>
                                        <i class="fas fa-excel"></i>
                                    </button>

                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Dữ liệu báo cáo</h4>
                <table id="tbl" class="table table-bordered table-hover table-striped" style="width: 100%">
                    <thead>
                        <tr>
                            <th style="width: 5%">STT</th>
                            <th>Số giấy phép</th>
                            <th>Tên dự án/cơ sở</th>
                            <th>Tên chủ đầu tư</th>
                            <th>Cơ quan cấp</th>
                            <th>Ngày cấp</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (ViewBag.Data != null)
                        {
                            @for (int i = 0; i < @ViewBag.Data.Count; i++)
                            {
                                <tr>
                                    <td>@(i + 1)</td>
                                    <td>@ViewBag.Data[i].SoGiayPhep</td>
                                    <td>@ViewBag.Data[i].TenDuAn</td>
                                    <td>@ViewBag.Data[i].TenDoanhNghiep</td>
                                    <td>@ViewBag.Data[i].CoQuanCap</td>
                                    <td>@ViewBag.Data[i].NgayCap</td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section Scripts{
<script type="text/javascript" src="//cdn.jsdelivr.net/momentjs/latest/moment-with-locales.min.js"></script>
}

QuanLyMoiTruong.WebApp/Views/BaoCao/BaoCaoChiTieuBaoVeMoiTruongKCN.cshtml
@using QuanLyMoiTruong.Application.Requests
@model BaoCaoBaoVeMoiTruongRequest;
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="pagetitle">
    <h1>Bảng 1.2 (Báo cáo BVMT KKT)</h1>
    <nav>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
            <li class="breadcrumb-item active">Bảng 1.2: Chỉ tiêu báo cáo về môi trường đối với Khu công nghiệp không thuộc khu kinh tế</li>
        </ol>
    </nav>
</div><!-- End Page Title -->
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <div class="row  pt-2">
                    <form asp-action="BaoCaoChiTieuBaoVeMoiTruongKCN" asp-controller="BaoCao" method="post" class="row g-3 needs-validation" novalidate>
                        <div class="col-6 col-md-6 col-lg-6 col-xl-8">
                            <div class="row  ttls-cm">
                                <div class="col-4">
                                    <label>Từ ngày báo cáo</label>
                                    <div class="ttls-content">
                                        <input type="date" class="form-control" asp-for="TuNgay" placeholder="Từ ngày">
                                    </div>
                                </div>
                                <div class="col-4">
                                    <label>Đến ngày báo cáo</label>
                                    <div class="ttls-content">
                                        <input type="date" class="form-control" asp-for="DenNgay" placeholder="Đến ngày">
                                    </div>
                                </div>
                                <div class="col-4">
                                    <label>Năm báo cáo</label>
                                    <div class="ttls-content">
                                        <select asp-for="Nam" class="form-control">
                                            <option value="0">Lựa chọn năm báo cáo</option>
                                            <option value="2018">Năm 2018</option>
                                            <option value="2019">Năm 2019</option>
                                            <option value="2020">Năm 2020</option>
                                            <option value="2021">Năm 2021</option>
                                            <option value="2022">Năm 2022</option>
                                            <option value="2023">Năm 2023</option>
                                            <option value="2024">Năm 2024</option>
                                            <option value="2025">Năm 2025</option>
                                            <option value="2026">Năm 2026</option>
                                            <option value="2027">Năm 2027</option>
                                        </select>                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-6 col-md-6 col-lg-6 col-xl-4">
                            <label></label>

                            <div class="ttls-cm">
                                <div class="ttls-content">
                                    <button class="btn btn-sm btn-primary waves-effect waves-light" type="submit" name="command" value="Search">
                                        <span>Tra cứu</span>
                                        <i class="fas fa-search"></i>
                                    </button>
                                    <button class="btn btn-sm btn-success waves-effect waves-light" type="submit" name="command" value="Export">
                                        <span>Xuất excel</span>
                                        <i class="fas fa-excel"></i>
                                    </button>

                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Dữ liệu báo cáo</h4>
                <table id="tbl" class="table table-bordered table-hover table-striped" style="width: 100%">
                    <thead>
                        <tr>
                            <th rowspan="2" style="width: 5%">STT</th>
                            <th rowspan="2">Tên Khu công nghiệp đang hoạt động</th>
                            <th rowspan="2">Địa chỉ</th>
                            <th rowspan="2">Tên chủ đầu tư</th>
                            <th rowspan="2">Số lượng cơ sở đang hoạt động</th>
                            <th rowspan="2">Tỷ lệ lấp đầy</th>
                            <th rowspan="2">Hệ thống thu gom nước mưa</th>
                            <th colspan="3">Xử lý nước thải</th>
                            <th colspan="3">Tổng lượng CTR phát sinh</th>
                            <th rowspan="2">Công trình phòng ngừa, ứng phó sự cố môi trường</th>
                            <th rowspan="2">Tỷ lệ cây xanh</th>
                        </tr>
                        <tr>
                            <th>Tổng lượng nước thải phát sinh</th>
                            <th>Đấu nối vào HTXLNT</th>
                            <th>Hệ thống quan trắc nước thải tự động, liên tục</th>
                            <th>Sinh hoạt (tấn/năm)</th>
                            <th>Công nghiệp thông thường (kg/năm)</th>
                            <th>Nguy hại (kg/năm)</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (ViewBag.Data != null)
                        {
                            @for (int i = 0; i < @ViewBag.Data.Count; i++)
                            {
                                <tr>
                                    <td>@(i + 1)</td>
                                    <td>@ViewBag.Data[i].TenKhuCongNghiep</td>
                                    <td>@ViewBag.Data[i].DiaChi</td>
                                    <td>@ViewBag.Data[i].TenChuDautu</td>
                                    <td>@ViewBag.Data[i].SoLuongCoSo</td>
                                    <td>@ViewBag.Data[i].TyLeLapDay</td>
                                    <td>@ViewBag.Data[i].HeThongThuGomNuocMua</td>
                                    <td>@ViewBag.Data[i].TongLuongNuocThai</td>
                                    <td>@ViewBag.Data[i].CongSuatThietKeHTXLNT</td>
                                    <td>@ViewBag.Data[i].HeThongQuanTracNuocThai</td>
                                    <td>@ViewBag.Data[i].ChatThaiRanSinhHoat</td>
                                    <td>@ViewBag.Data[i].ChatThaiRanCongNghiep</td>
                                    <td>@ViewBag.Data[i].ChatThaiRanNguyHai</td>
                                    <td>@ViewBag.Data[i].CongTrinhPhongNgua</td>
                                    <td>@ViewBag.Data[i].TyLeCayXanh</td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section Scripts{
<script type="text/javascript" src="//cdn.jsdelivr.net/momentjs/latest/moment-with-locales.min.js"></script>
}

QuanLyMoiTruong.WebApp/Views/BaoCao/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}